### ISSUE TITLE
Error: font family not found in Windows font database

### ISSUE THREAD

**Issue by ArthurZ** [GuangchuangYu/meme#1]
On Windows 7 64 Pro, up-to-date, latest R, no matter what font I choose I get error:
`"font family not found in Windows font database"`
The fonts tried: Arial, Courier, etc. that are indeed registered in the system.

**Comment by Arvinlike** [comment]
Hello, my computer is Windows 10, at begin i face the same problem, later , i add a line of code 
like "windowsFonts("Arial" = windowsFont("Arial"))", 
you can try it

**Comment by GuangchuangYu** [comment]
the post, https://stackoverflow.com/questions/34522732/changing-fonts-in-ggplot2, is also useful.
